### ISSUE TITLE
[BUG] Victoria unable to authenticate with Azure

### ISSUE THREAD

**Issue by amalve** [glasswall-sre/victoria#37] opened 2021-01-13 10:19 UTC
**Describe the bug**

victoria commands are failing in CLI

1. Logged on to Azure with `az login` successfully.
2. Ran this command `victoria -h` or `victoria`.
3. ERROR: Unable to authenticate via Azure CLI, have you logged in with 'az login'?

**To Reproduce**

- followed the ReadME guide to configure victoria. 
- added AZURE_STORAGE_CONNECTION_STRING in the PATH variable.
- In CLI following the below steps
- az login
- browser opens
- logged in with user credentials successfully.
- `victoria -h` command returned with CLI output
- ERROR: Unable to authenticate via Azure CLI, have you logged in with 'az login'?

**Expected behavior**
After using command `victoria -h` it should output and display help options for victoria. 

**CLI output**
ERROR: Unable to authenticate via Azure CLI, have you logged in with 'az login'?

**Platform:**
 - OS: Mac OS
 - Shell: zsh
 - Victoria version: 0.8.3
 - Python version: Python 3.7.9

**Additional context**

**Comment by AshKapow** [comment] 2021-01-20 09:05
We believe this error is related to a missing pre-req for victoria
`azure-cli-core`

**Comment by amalve** [comment] 2021-01-21 16:45
Installed the prerequisite for victoria `azure-cli-core`. Now, able to run the victoria help commands.

Thank you!

**Comment by AshKapow** [comment] 2021-01-21 16:51
Re-opening as we still need to fix the root cause of the issue

**Comment by AshKapow** [comment] 2021-01-25 10:46
There also could be an issue with MFA on Azure

**Comment by mukulgupta2138** [comment] 2021-01-27 12:27
This seems to be working for now with fresh installation:
![image](https://user-images.githubusercontent.com/77505708/105990881-1d3a8700-60c9-11eb-9bd8-1afac42f0146.png)

**Comment by mukulgupta2138** [comment] 2021-01-29 07:35
@AshKapow Created a PR around this https://github.com/glasswall-sre/victoria/pull/38 Kindly have a look. Thanks

**Comment by mukulgupta2138** [comment] 2021-01-29 09:48
This is now fixed, closing this issue

**Closed by mukulgupta2138** 2021-01-29 09:48 UTC
Labels: bug
